name: haskoin-store
version: 0.19.6
synopsis: Storage and index for Bitcoin and Bitcoin Cash
description: Store blocks, transactions, and balances for Bitcoin or Bitcoin Cash, and make that information via REST API.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: jprupp@protonmail.ch
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin-store.git
homepage: http://github.com/haskoin/haskoin-store#readme
bug-reports: http://github.com/haskoin/haskoin-store/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - aeson
  - base >=4.9 && <5
  - bytestring
  - cereal
  - containers
  - conduit
  - data-default
  - hashable
  - haskoin-core >= 0.9.7
  - haskoin-node
  - http-types
  - monad-logger
  - mtl
  - network
  - nqe
  - parallel
  - random
  - resourcet
  - rocksdb-haskell
  - rocksdb-query >= 0.3.0
  - scotty
  - string-conversions
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers
  - wai
  - warp
library:
  source-dirs: src
  generated-exposed-modules:
    - Paths_haskoin_store
  exposed-modules:
    - Haskoin.Store
executables:
  haskoin-store:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-store
      - filepath
      - optparse-applicative
tests:
  haskoin-store-test:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - haskoin-store
