name: haskoin-store
version: 1.0.0
synopsis: Storage and index for Bitcoin wallets
description: 'Store all blocks, transactions, and addresses required for a Bitcoin or Bitcoin Cash wallet or block explorer to function.'
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin.git
homepage: http://github.com/haskoin/haskoin#readme
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
- README.md
- CHANGELOG.md
dependencies:
- aeson
- base >=4.7 && <5
- bytestring
- cereal
- haskoin-core
- haskoin-node
- monad-logger
- mtl
- nqe
- rocksdb-haskell
- unliftio
library:
  source-dirs: src
  exposed-modules:
  - Network.Haskoin.Store
  dependencies:
  - aeson
  - containers
  - network
  - rocksdb-query
  - string-conversions
  - transformers
executables:
  haskoin-store:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
    - filepath
    - haskoin-store
    - http-types
    - optparse-applicative
    - scotty
    - string-conversions
    - text
tests:
  haskoin-store-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskoin-store
    - hspec
