name: haskoin-store
version: 0.1.1
synopsis: Storage and index for Bitcoin and Bitcoin Cash
description: Store blocks, transactions, and balances for Bitcoin or Bitcoin Cash, and make that information via REST API.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin.git
homepage: http://github.com/haskoin/haskoin#readme
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - aeson
  - base >=4.7 && <5
  - bytestring
  - cereal
  - conduit
  - directory
  - filepath
  - haskoin-core
  - haskoin-node
  - hspec
  - http-types
  - monad-logger
  - mtl
  - nqe
  - optparse-applicative
  - random
  - rocksdb-haskell
  - scotty
  - string-conversions
  - text
  - time
  - unliftio
library:
  source-dirs: src
  exposed-modules:
    - Network.Haskoin.Store
  dependencies:
    - aeson
    - containers
    - network
    - rocksdb-query
    - string-conversions
    - transformers
executables:
  haskoin-store:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-store
tests:
  haskoin-store-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-store
